version: '3'

services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  whoami:
      image: traefik/whoami
      ports:
        - "8080:80"
