version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: nginx
    ports:
      # The HTTP port
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  whoami:
      # A container that exposes an API to show its IP address
      image: traefik/whoami
      ports:
        - "8080:80"
