version: '3'

services:
  reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  whoami:
      image: traefik/whoami
      ports:
        - "8080:80"
